# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction_systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this address belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction_systems.Company', verbose_name='Company'),
        ),
    ]
